project:
  type: website
  output-dir: D:/SYNC/Sync/website/E-Portfolio-main

website:
  title: "Chris Mulverhill"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

