project:
  type: website
  output-dir: D:/SYNC/Sync/website/portfolio

website:
  title: "Chris Mulverhill, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Example Projects

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    linkcolor: orange
    

editor: visual

